Populate CFG node types
mhorod/cacophony pull request #116
Opened 2024-11-05 20:52 UTC by AHGIJMKLKKZNPJKQR

2024-11-05 21:21 UTC, Rafi0221 commented on src/main/kotlin/cacophony/controlflow/CFGNode.kt
> +    sealed class Lesser(
Less? same below

2024-11-06 19:24 UTC, KacperTopolski commented on src/main/kotlin/cacophony/controlflow/CFGNode.kt
> +        vararg val nodes: CFGNode,
I think we should avoid varargs in primary constructors and simply use lists. Maybe add it as a secondary contructor.

2024-11-06 21:39 UTC, Rafi0221 requested changes
Please add push and pop nodes.

2024-11-07 17:44 UTC, KacperTopolski commented on src/main/kotlin/cacophony/controlflow/CFGNode.kt
> +    // NOTE: Pop may be unncessary since it can be done via Assignment
Typo.

2024-11-07 17:45 UTC, KacperTopolski commented on src/main/kotlin/cacophony/controlflow/CFGNode.kt
> +    sealed interface BitwiseOperator : Unconditional
We do not support bitwise operators.

2024-11-07 18:55 UTC, Rafi0221 approved these changes

2024-11-07 19:36 UTC, merged