Add structures to AST and grammar
mhorod/cacophony pull request #210
Opened 2024-12-03 17:29 UTC by AHGIJMKLKKZNPJKQR

TODO: some tests in AST, NameResolver, OverloadResolver and CallGraph :zzz:

2024-12-04 13:31 UTC, SebastianSpyrzewski requested changes
I see no support for access to struct fields, starting from no lexer token '.' - will it be implemented later?

2024-12-04 13:31 UTC, SebastianSpyrzewski commented on src/main/kotlin/cacophony/semantic/syntaxtree/SyntaxTree.kt
> +    class Struct(range: Pair<Location, Location>, val fields: Map<String, Type>) : Type(range) {
maybe this could be `Type.Structural` to match naming convention with `Type.basic` and `Type.Functional`

2024-12-04 13:33 UTC, AHGIJMKLKKZNPJKQR commented
@SebastianSpyrzewski 
> I see no support for access to struct fields, starting from no lexer token '.' - will it be implemented later?
Yeah, I decided to separate that to a second PR, to not make this one too bulky and it seems to be a clean way to separate the code

2024-12-04 23:32 UTC, jjaworska reviewed
Overall looks great! Really great refactors! but I have this one question below

2024-12-04 23:32 UTC, jjaworska commented on src/main/kotlin/cacophony/semantic/names/NameResolver.kt
> +                node.fields.values.forEach { traverseAst(it, true) }
It seems odd to me that we don't use field identifiers here?

2024-12-05 13:27 UTC, jjaworska commented on src/test/kotlin/cacophony/semantic/names/NameResolverTest.kt
> +                // let a = {x = let b = 2, y = c};
maybe add a bUse?

2024-12-05 13:43 UTC, jjaworska approved these changes
Great contribution! :confetti_ball:

2024-12-05 13:43 UTC, merged