Adjusted to specification
mhorod/cacophony pull request #30
Opened 2024-10-15 12:57 UTC by FilipKon13

2024-10-15 12:59 UTC, FilipKon13 commented
Should resolve #28 and #26

2024-10-15 16:40 UTC, Giselus commented
LGTM :thumbsup:  It's not that important to fix everything now, as we may find errors (if we still have some) when we'll try to test these examples.

2024-10-16 19:10 UTC, Giselus requested changes

2024-10-17 07:39 UTC, Giselus approved these changes

2024-10-17 07:54 UTC, merged