Added regex to NFA conversion
mhorod/cacophony pull request #41
Opened 2024-10-19 14:57 UTC by jjaworska

2024-10-19 17:52 UTC, Giselus requested changes
Looks mainly good, only cosmetic changes. But please, fix the build, as it's currently failing due to linter.

2024-10-19 17:52 UTC, Giselus commented on src/main/kotlin/cacophony/automata/NFAConstructor.kt
> +// implementation relies on the fact that the initial state will always have number 0
Please start comment with uppercase letter and end it with dot to stay consistent with other PRs.

2024-10-19 17:52 UTC, Giselus commented on src/test/kotlin/cacophony/automata/NFAConstructorTest.kt
> +    fun `Simple atomic regex test`() {
We also start test function names from lowercase letter.

2024-10-19 17:52 UTC, Giselus commented on src/main/kotlin/cacophony/automata/NFAConstructor.kt
Looks good, but I'm not sure about this file name. There is already simpleDFA class, and it's in the DFA.kt. It doesn't have to be like that, but usally filename is the same as main interface/class name, and we don't have anything like NFAConstructor. Maybe we can move buildNFAFromRegex to NFA.kt and rename this file to simpleNFA.kt? Just suggestion, probably can be done differently.

2024-10-19 21:44 UTC, Giselus requested changes

2024-10-19 21:44 UTC, Giselus commented on src/main/kotlin/cacophony/automata/NFAConstructor.kt
> +            var prods: Map<Pair<Int, Char>, List<Int>> = mapOf()
Maybe it should be mutableMap?

2024-10-20 22:56 UTC, jjaworska commented on src/main/kotlin/cacophony/automata/NFAConstructor.kt
Following the convention which was chosen for DFA's, I moved the SimpleNFA class to the NFA.kt, but left the implementation in a separate file, didn't really have a name better idea

2024-10-20 23:10 UTC, Giselus approved these changes

2024-10-20 23:10 UTC, merged